M48
; DRILL file {KiCad 9.0.8} date 2026-03-25T13:51:49-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-25T13:51:49-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1732
%
G90
G05
T1
X2.1217Y-2.1445
X2.4217Y-1.9445
T2
X1.2874Y-1.1102
X1.2874Y-3.0787
X3.2559Y-1.1102
X3.2559Y-3.0787
M30
